language: python
matrix:
  include:
   - python: 3.4
     env: TOXENV=py34-django110
   - python: 3.4
     env: TOXENV=py34-django111
   - python: 3.4
     env: TOXENV=py34-django20
   - python: 3.5
     env: TOXENV=py35-django110
   - python: 3.5
     env: TOXENV=py35-django111
   - python: 3.5
     env: TOXENV=py35-django20
   - python: 3.6
     env: TOXENV=py36-django110
   - python: 3.6
     env: TOXENV=py36-django111
   - python: 3.6
     env: TOXENV=py36-django20
   - python: 3.6
     env: TOXENV=flake8

install:
  - pip install tox
  - if test "$TOXENV" = py36-django20; then pip install coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py36-django20; then coveralls ; fi
